/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const ChatMessageEntry = IDL.Record({
  'from' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : AppointmentStatus,
  'date' : Time,
  'time' : IDL.Text,
  'description' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'chatHistory' : IDL.Vec(ChatMessageEntry),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func([Appointment], [], []),
  'deleteAppointment' : IDL.Func([], [], []),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateAppointment' : IDL.Func([Appointment], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChatMessageEntry = IDL.Record({
    'from' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : AppointmentStatus,
    'date' : Time,
    'time' : IDL.Text,
    'description' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'chatHistory' : IDL.Vec(ChatMessageEntry),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func([Appointment], [], []),
    'deleteAppointment' : IDL.Func([], [], []),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateAppointment' : IDL.Func([Appointment], [], []),
  });
};

export const init = ({ IDL }) => { return []; };